/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import Classes.*;
import Controller.*;
import javax.swing.DefaultListModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author alejos17
 */
public class start extends javax.swing.JFrame {
    
    Control control = new Control();  //Instancia de Controller 
    public String codesM;
    
    /**
     * Creates new form start
     */
    public start() {
        initComponents();
        //control.Init();
        this.Listar("Cliente", null);
        this.Listar("Inventario", null);
        //this.Listar("Cuenta");
        //this.Listar("ListaCuentaClientes");
        //this.Listar("Pedido");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnCrearCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clienteList = new javax.swing.JList<>();
        btnBuscarCLiente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnBorrarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtidCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cuentasLIst = new javax.swing.JScrollPane();
        listaCuentas = new javax.swing.JList<>();
        btnCrearCuenta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtidCuenta = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        cbTipoCuenta = new javax.swing.JComboBox<>();
        cbCliente = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCuentaClientes = new javax.swing.JList<>();
        btnBuscarCuenta = new javax.swing.JButton();
        btnEditarCuenta = new javax.swing.JButton();
        jLabelCuentaCliente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnBorrarCuenta = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnAgregarInv = new javax.swing.JButton();
        btnBuscarInv = new javax.swing.JButton();
        btnEditarInv = new javax.swing.JButton();
        btnBorrarInv = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtxtidinv = new javax.swing.JTextField();
        cbcatinv = new javax.swing.JComboBox<>();
        jtxtprodinv = new javax.swing.JTextField();
        jtxtvunit = new javax.swing.JTextField();
        jtxtextinv = new javax.swing.JTextField();
        jtxtiva = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        invList = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearCliente.setText("Crear");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });

        clienteList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Clientes Actuales" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        clienteList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clienteList);

        btnBuscarCLiente.setText("Buscar");
        btnBuscarCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCLienteActionPerformed(evt);
            }
        });

        btnEditarCliente.setText("Editar");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        btnBorrarCliente.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnBorrarCliente.setText("Borrar");
        btnBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Código del Cliente");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Dirección");

        jLabel5.setText("Teléfono");

        jLabel6.setText("Correo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido)
                            .addComponent(txtDireccion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(txtidCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEditarCliente)
                                    .addComponent(btnCrearCliente))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarCLiente)
                                    .addComponent(btnBorrarCliente))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefono))))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrearCliente)
                            .addComponent(btnBuscarCLiente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarCliente)
                            .addComponent(btnBorrarCliente))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel1);

        listaCuentas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cuentas con Saldo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        cuentasLIst.setViewportView(listaCuentas);

        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        jLabel8.setText("Código de Cuenta");

        jLabel9.setText("Tipo de Cuenta");

        jLabel10.setText("Saldo en Cuenta");

        cbTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Corriente", "Ahorros" }));

        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });

        jLabel11.setText("Cliente");

        listaCuentaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCuentaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaCuentaClientes);

        btnBuscarCuenta.setText("Buscar Cuenta");
        btnBuscarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentaActionPerformed(evt);
            }
        });

        btnEditarCuenta.setText("Editar Cuenta");
        btnEditarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCuentaActionPerformed(evt);
            }
        });

        jLabelCuentaCliente.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel12.setText("Cantidad Total de Cuentas en el sistema");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel13.setText("Cuentas del Cliente");

        btnBorrarCuenta.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnBorrarCuenta.setText("Borrar Cuenta del Cliente");
        btnBorrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCuentaActionPerformed(evt);
            }
        });

        jLabel14.setText("Haga doble clic para editar una cuenta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCrearCuenta)
                                    .addComponent(btnBuscarCuenta)
                                    .addComponent(btnEditarCuenta))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtidCuenta))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrarCuenta)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(426, 426, 426)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCliente, 0, 326, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelCuentaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cuentasLIst, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCrearCuenta)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtidCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jLabelCuentaCliente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscarCuenta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBorrarCuenta))
                    .addComponent(btnEditarCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuentasLIst, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuentas", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pedidos", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cobros", jPanel4);

        btnAgregarInv.setText("Agregar");
        btnAgregarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarInvActionPerformed(evt);
            }
        });

        btnBuscarInv.setText("Buscar");
        btnBuscarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInvActionPerformed(evt);
            }
        });

        btnEditarInv.setText("Editar");
        btnEditarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarInvActionPerformed(evt);
            }
        });

        btnBorrarInv.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnBorrarInv.setText("Borrar");
        btnBorrarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarInvActionPerformed(evt);
            }
        });

        jLabel15.setText("ID Producto");

        jLabel16.setText("Categoria");

        jLabel17.setText("Producto");

        jLabel18.setText("Valor Unitario");

        jLabel19.setText("IVA");

        jLabel20.setText("Existencia");

        cbcatinv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrónica", "Software", "Videogames" }));

        invList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(invList);

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel21.setText("Haga doble click para editar un Producto del Inventario");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtidinv)
                            .addComponent(cbcatinv, 0, 150, Short.MAX_VALUE)
                            .addComponent(jtxtprodinv)
                            .addComponent(jtxtvunit)
                            .addComponent(jtxtextinv)
                            .addComponent(jtxtiva)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBorrarInv)
                            .addComponent(btnEditarInv))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarInv)
                            .addComponent(btnEditarInv))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarInv)
                            .addComponent(btnBorrarInv))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jtxtidinv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbcatinv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jtxtprodinv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jtxtvunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jtxtiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jtxtextinv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventario", jPanel5);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gestión de Clientes / Pedidos");

        btnCerrar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        // TODO add your handling code here:
        try {     //Try para encapsular errores en este caso por si ponen mal la fecha en el campo bornYear
            String idCliente = txtidCliente.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String direccion = txtDireccion.getText();
            String telefono = txtTelefono.getText();
            String correo = txtCorreo.getText();
            
            
            //Condicional para no agregar el objeto perro nuevo hasta que los campos tengan info, las selecciones no porque ya tienen algo seleccionado
            if (idCliente.equals("") || nombre.equals("") || apellido.equals("") || direccion.equals("") || telefono.equals("") || correo.equals("")){
                JOptionPane.showMessageDialog(this, "** ERROR ** -- Campos Vacíos -- Por favor diligencie todos los campos");
            }else{
                clsCliente cliente = new clsCliente(idCliente, nombre, apellido, direccion, telefono, correo);
                control.CrearCliente(cliente);
                
                this.Listar("Cliente", null);
                this.borrarCampos();
                JOptionPane.showMessageDialog(this, "El nuevo cliente ha sido creado con éxito!");
            }
            
        }catch (Exception e){   //Mensaje a desplegar de error
            JOptionPane.showMessageDialog(this, "*** ERROR ****");
        }
        
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
        try {     //Try para encapsular errores en este caso por si ponen mal la fecha en el campo bornYear
            String idCuenta = txtidCuenta.getText();
            String tipoCuenta = cbTipoCuenta.getSelectedItem().toString();
            int saldo = Integer.parseInt(txtSaldo.getText());
            String idcuentacliente = cbCliente.getSelectedItem().toString();
            
            //Condicional para no agregar el objeto perro nuevo hasta que los campos tengan info, las selecciones no porque ya tienen algo seleccionado
            if (idCuenta.equals("") || tipoCuenta.equals("")){
                JOptionPane.showMessageDialog(this, "** ERROR ** -- Campos Vacíos -- Por favor diligencie todos los campos");
            }else{
                clsCuentas cuenta = new clsCuentas(idCuenta, tipoCuenta, saldo, idcuentacliente);  //Crea instancia de Cuenta para crear
                control.CrearCuenta(cuenta);  //Envia al controller la cuenta a crear
                //this.Listar("Cuenta");
                //this.Listar("ListaCuentaClientes");
                this.borrarCampos();
                JOptionPane.showMessageDialog(this, "La Cuenta ha sido creada y asignada al cliente con éxito!");
            }
            
        }catch (Exception e){   //Mensaje a desplegar de error
            JOptionPane.showMessageDialog(this, "*** ERROR ****");
        }
        
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnBuscarCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCLienteActionPerformed
        // TODO add your handling code here:
        String code = txtidCliente.getText();  //Campo de busqueda
        codesM = txtidCliente.getText();
        System.out.println(codesM);
        clsCliente cliente = control.BuscarCliente(code); //Instancia cliente para ir a control a buscar 
        
        //Si cliente retorna NUll quiere decir que no encontro cliente y genera mensaje de lo contrario lo muestra en los text
        if (cliente == null){
            JOptionPane.showMessageDialog(this, "El código de Cliente no existe, intente de nuevo!");
        }else{
            txtNombre.setText(cliente.getNombre());
            txtApellido.setText(cliente.getApellido());
            txtDireccion.setText(cliente.getDireccion());
            txtTelefono.setText(cliente.getTelefono());
            txtCorreo.setText(cliente.getCorreo()); 
        }
    }//GEN-LAST:event_btnBuscarCLienteActionPerformed

    private void clienteListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteListMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_clienteListMouseClicked

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        // TODO add your handling code here:
        String code = txtidCliente.getText();  //Campo de busqueda
        String tipo = "Cliente";   // Tipo de busqueda
        
        try {     //Try para encapsular errores en este caso por si ponen mal la fecha en el campo bornYear
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String direccion = txtDireccion.getText();
            String telefono = txtTelefono.getText();
            String correo = txtCorreo.getText();
            
            
            //Condicional para no agregar el objeto perro nuevo hasta que los campos tengan info, las selecciones no porque ya tienen algo seleccionado
            if (code.equals("") || nombre.equals("") || apellido.equals("") || direccion.equals("") || telefono.equals("") || correo.equals("")){
                JOptionPane.showMessageDialog(this, "** ERROR ** -- Campos Vacíos -- Por favor diligencie todos los campos");
            }else{
                clsCliente clienteM = new clsCliente(code, nombre, apellido, direccion, telefono, correo);
                control.EditarCliente(codesM, clienteM);
                
                this.Listar("Cliente", null);
                this.borrarCampos();
                JOptionPane.showMessageDialog(this, "El cliente ha sido cambiado con éxito!");
            }
            
        }catch (Exception e){   //Mensaje a desplegar de error
            JOptionPane.showMessageDialog(this, "*** ERROR ****");
        }
        
        codesM = "";
        System.out.println(codesM);
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarClienteActionPerformed
        // TODO add your handling code here:
        String code = txtidCliente.getText();  //Campo de busqueda
        String tipo = "Cliente";   // Tipo de busqueda
        boolean found = control.Borrar(tipo, code); //Instancia cliente para ir a control a buscar 
        
        //Si found es false, mensaje de cliente no exite si es true se borro bien.
        if (found == false){
            JOptionPane.showMessageDialog(this, "El código de Cliente no existe, intente de nuevo!");
        }else{
            this.borrarCampos();
            this.Listar("Cliente", null);
            JOptionPane.showMessageDialog(this, "El Cliente ha sido eliminado con éxito!");
        }
    }//GEN-LAST:event_btnBorrarClienteActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentaActionPerformed
        // TODO add your handling code here:
        String code = txtidCuenta.getText();  //Campo de busqueda
        codesM = txtidCuenta.getText();
        System.out.println(codesM);
        clsCuentas cuenta = control.BuscarCuenta(code); //Instancia cliente para ir a control a buscar 
        
        //Si cliente retorna NUll quiere decir que no encontro cliente y genera mensaje de lo contrario lo muestra en los text
        if (cuenta == null){
            JOptionPane.showMessageDialog(this, "El código de la Cuenta no existe, intente de nuevo!");
        }else{
            cbTipoCuenta.setSelectedItem(cuenta.getCuenta());
            txtSaldo.setText(cuenta.getSaldo()+"");
            cbCliente.setSelectedItem(cuenta.getIdcuentacliente());
        }
    
    }//GEN-LAST:event_btnBuscarCuentaActionPerformed

    private void btnEditarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCuentaActionPerformed
        // TODO add your handling code here:
        String code = txtidCuenta.getText();  //Campo de busqueda
        String cuentaCliente = cbCliente.getSelectedItem().toString();
        try {     //Try para encapsular errores en este caso por si ponen mal la fecha en el campo bornYear
            String tipoCuenta = cbTipoCuenta.getSelectedItem().toString();
            int saldo = Integer.parseInt(txtSaldo.getText());
            
            //Condicional para no agregar el objeto perro nuevo hasta que los campos tengan info, las selecciones no porque ya tienen algo seleccionado
            if (code.equals("") || tipoCuenta.equals("")){
                JOptionPane.showMessageDialog(this, "** ERROR ** -- Campos Vacíos -- Por favor diligencie todos los campos");
            }else{
                clsCuentas cuentaM = new clsCuentas(code,tipoCuenta, saldo, cuentaCliente);
                control.EditarCuenta(codesM, cuentaM);
                this.Listar("Cuenta", null);
                this.Listar("ListaCuentaClientes", cuentaCliente);
                this.borrarCampos();
                JOptionPane.showMessageDialog(this, "La Cuenta ha sido modificada con éxito!");
            }
            
        }catch (Exception e){   //Mensaje a desplegar de error
            JOptionPane.showMessageDialog(this, "*** ERROR ****");
        }
         codesM = "";
         System.out.println(codesM);
    }//GEN-LAST:event_btnEditarCuentaActionPerformed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        // TODO add your handling code here:
        String code = cbCliente.getSelectedItem().toString();  //Campo de busqueda
        clsCliente cliente = control.BuscarCliente(code); //Instancia cliente para ir a control a buscar 
        jLabelCuentaCliente.setText(cliente.getNombre()+" "+cliente.getApellido());
        this.Listar("ListaCuentaClientes", code);
    }//GEN-LAST:event_cbClienteActionPerformed

    private void btnBorrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCuentaActionPerformed
        // TODO add your handling code here:
        String code = txtidCuenta.getText();  //Campo de busqueda
        String tipo = "Cuenta";   // Tipo de busqueda
        boolean found = control.Borrar(tipo, code); //Instancia cliente para ir a control a buscar 
        
        //Si found es false, mensaje de cliente no exite si es true se borro bien.
        if (found == false){
            JOptionPane.showMessageDialog(this, "La Cuenta no existe, intente de nuevo!");
        }else{
            this.borrarCampos();
            this.Listar("ListaCuentaClientes", cbCliente.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "La Cuenta ha sido eliminada con éxito!");
        }    
    }//GEN-LAST:event_btnBorrarCuentaActionPerformed

    private void listaCuentaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCuentaClientesMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {   //Detectar el doble click en la lista para cargar la cuenta seleccionada
            int index = listaCuentaClientes.locationToIndex(evt.getPoint());  //Index para guardar la posicion donde se hace el doble click
            String code = listaCuentaClientes.getSelectedValue();   //Guarda la cadena seleccionada
            String[] parts = code.split(" ");  //Cortar la cadena en el primer espacio que es el id de cuenta
            String part1 = parts[0];   //Solo se guarda la primera parte id cuenta
            txtidCuenta.setText(part1);  //Se pone en el text de idcuenta para visualizacion del usuario
            codesM = part1;
            clsCuentas cuenta = control.BuscarCuenta(part1); //Instancia cliente para ir a control a buscar 
            cbTipoCuenta.setSelectedItem(cuenta.getCuenta());   //Se traen los valores de la busqueda.
            txtSaldo.setText(cuenta.getSaldo()+"");
            cbCliente.setSelectedItem(cuenta.getIdcuentacliente());
        }
    }//GEN-LAST:event_listaCuentaClientesMouseClicked

    private void btnAgregarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarInvActionPerformed
        // TODO add your handling code here:
        try {     //Try para encapsular errores en este caso por si ponen mal la fecha en el campo bornYear
            String idProducto = jtxtidinv.getText();
            String categoria = cbcatinv.getSelectedItem().toString();
            String producto = jtxtprodinv.getText();
            double valorunitario = Double.parseDouble(jtxtvunit.getText());
            double iva = Double.parseDouble(jtxtiva.getText());
            int existencia = Integer.parseInt(jtxtextinv.getText()); 
            
            
            //Condicional para no agregar el objeto perro nuevo hasta que los campos tengan info, las selecciones no porque ya tienen algo seleccionado
            if (idProducto.equals("") || producto.equals("") ){
                JOptionPane.showMessageDialog(this, "** ERROR ** -- Campos Vacíos -- Por favor diligencie todos los campos");
            }else{
                clsInventario inv = new clsInventario(idProducto, categoria, producto, existencia, iva, valorunitario);
                control.AgregarInventario(inv);
                this.Listar("Inventario", null);
                this.borrarCampos();
                JOptionPane.showMessageDialog(this, "El producto ha sido agredado al inventario con éxito!");
            }
            
        }catch (Exception e){   //Mensaje a desplegar de error
            JOptionPane.showMessageDialog(this, "*** ERROR ****");
        }
    }//GEN-LAST:event_btnAgregarInvActionPerformed

    private void btnBuscarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInvActionPerformed
        // TODO add your handling code here:
        String code = jtxtidinv.getText(); //Campo de busqueda
        codesM = jtxtidinv.getText();
        System.out.println(codesM);
        clsInventario inv = control.BuscarInv(code);
        
        //Si cliente retorna NUll quiere decir que no encontro cliente y genera mensaje de lo contrario lo muestra en los text
        if (inv == null){
            JOptionPane.showMessageDialog(this, "El código de Producto no existe en Inventario, intente de nuevo!");
        }else{
            jtxtidinv.setText(inv.getIdProducto());
            cbcatinv.setSelectedItem(inv.getCategoria());
            jtxtprodinv.setText(inv.getProducto());
            jtxtvunit.setText(inv.getValorUnit()+"");
            jtxtiva.setText(inv.getIva()+"");
            jtxtextinv.setText(inv.getCant_ext()+"");
        }
    }//GEN-LAST:event_btnBuscarInvActionPerformed

    private void btnEditarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarInvActionPerformed
        // TODO add your handling code here:
        String code = jtxtidinv.getText();  //Campo de busqueda
        String tipo = "Inventario";   // Tipo de busqueda
        
        try {     //Try para encapsular errores en este caso por si ponen mal la fecha en el campo bornYear
            String idProducto = jtxtidinv.getText();
            String categoria = cbcatinv.getSelectedItem().toString();
            String producto = jtxtprodinv.getText();
            double valorunitario = Double.parseDouble(jtxtvunit.getText());
            double iva = Double.parseDouble(jtxtiva.getText());
            int existencia = Integer.parseInt(jtxtextinv.getText()); 
            
            
            //Condicional para no agregar el objeto perro nuevo hasta que los campos tengan info, las selecciones no porque ya tienen algo seleccionado
            if (idProducto.equals("") || producto.equals("") ){
                JOptionPane.showMessageDialog(this, "** ERROR ** -- Campos Vacíos -- Por favor diligencie todos los campos");
            }else{
                clsInventario invM = new clsInventario(idProducto, categoria, producto, existencia, iva, valorunitario);
                control.EditarInventario(codesM, invM);
                
                this.Listar("Inventario", null);
                this.borrarCampos();
                JOptionPane.showMessageDialog(this, "El producto ha sido cambiado con éxito en el inventario!");
            }
            
        }catch (Exception e){   //Mensaje a desplegar de error
            JOptionPane.showMessageDialog(this, "*** ERROR ****");
        }
        
        codesM = "";
        System.out.println(codesM);
    }//GEN-LAST:event_btnEditarInvActionPerformed

    private void btnBorrarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarInvActionPerformed
        // TODO add your handling code here:
        String code = jtxtidinv.getText();  //Campo de busqueda
        String tipo = "Inventario";   // Tipo de busqueda
        boolean found = control.Borrar(tipo, code); //Instancia cliente para ir a control a buscar 
        
        //Si found es false, mensaje de cliente no exite si es true se borro bien.
        if (found == false){
            JOptionPane.showMessageDialog(this, "El código del Producto no existe en Inventario, intente de nuevo!");
        }else{
            this.borrarCampos();
            this.Listar("Inventario", null);
            JOptionPane.showMessageDialog(this, "El Producto ha sido eliminado con éxito del Inventario!");
        }
    }//GEN-LAST:event_btnBorrarInvActionPerformed

    private void invListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invListMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {   //Detectar el doble click en la lista para cargar la cuenta seleccionada
            int index = invList.locationToIndex(evt.getPoint());  //Index para guardar la posicion donde se hace el doble click
            String code = invList.getSelectedValue();   //Guarda la cadena seleccionada
            String[] parts = code.split(" ");  //Cortar la cadena en el primer espacio que es el id de cuenta
            String part1 = parts[0];   //Solo se guarda la primera parte id cuenta
            jtxtidinv.setText(part1);  //Se pone en el text de idcuenta para visualizacion del usuario
            codesM = part1;
            clsInventario inv = control.BuscarInv(part1); //Instancia cliente para ir a control a buscar 
            cbcatinv.setSelectedItem(inv.getCategoria());   //Se traen los valores de la busqueda.
            jtxtprodinv.setText(inv.getProducto());
            jtxtvunit.setText(inv.getValorUnit()+"");
            jtxtiva.setText(inv.getIva()+"");
            jtxtextinv.setText(inv.getCant_ext()+"");    
        }
    }//GEN-LAST:event_invListMouseClicked

    private void Listar(String tipo, String code){
        DefaultListModel model = new DefaultListModel();
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        
        switch (tipo){
            case "Cliente":
                model = control.Listar("Cliente", null);
                clienteList.setModel(model);   //La lista toma el modelo de lista model
                model2 = control.ListarComboBoxClientes();
                cbCliente.setModel(model2);
            case "Cuenta":
                model = control.Listar("Cuenta", null);
                listaCuentas.setModel(model);
            case "ListaCuentaClientes":
                model = control.Listar("ListaCuentaClientes", code);
                listaCuentaClientes.setModel(model);
            case "Inventario":
                model = control.Listar("Inventario", null);
                invList.setModel(model);
            case "Pedido":
                model = control.Listar("Pedido", null);
                //listaPedidos.setModel(model);
            
        }
        
        
    }
    
    public void borrarCampos(){
        txtidCliente.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtidCuenta.setText("");
        txtSaldo.setText("");
        
        jtxtidinv.setText("");
        jtxtprodinv.setText("");
        jtxtvunit.setText("");
        jtxtiva.setText("");
        jtxtextinv.setText("");
    }
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarInv;
    private javax.swing.JButton btnBorrarCliente;
    private javax.swing.JButton btnBorrarCuenta;
    private javax.swing.JButton btnBorrarInv;
    private javax.swing.JButton btnBuscarCLiente;
    private javax.swing.JButton btnBuscarCuenta;
    private javax.swing.JButton btnBuscarInv;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEditarCuenta;
    private javax.swing.JButton btnEditarInv;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbTipoCuenta;
    private javax.swing.JComboBox<String> cbcatinv;
    private javax.swing.JList<String> clienteList;
    private javax.swing.JScrollPane cuentasLIst;
    private javax.swing.JList<String> invList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCuentaCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jtxtextinv;
    private javax.swing.JTextField jtxtidinv;
    private javax.swing.JTextField jtxtiva;
    private javax.swing.JTextField jtxtprodinv;
    private javax.swing.JTextField jtxtvunit;
    private javax.swing.JList<String> listaCuentaClientes;
    private javax.swing.JList<String> listaCuentas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtidCliente;
    private javax.swing.JTextField txtidCuenta;
    // End of variables declaration//GEN-END:variables
}
